//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class alt_tov
    {
        public int id_tov { get; set; }
        public int id_serv { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
