//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class alt_postavok
    {
        public int id_tovar { get; set; }
        public int id_postavok { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Поставки Поставки { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
