//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставки()
        {
            this.alt_postavok = new HashSet<alt_postavok>();
        }
    
        public int id_Supplies { get; set; }
        public int id_supplier { get; set; }
        public System.DateTime date { get; set; }
        public int count { get; set; }
        public int price { get; set; }
        public Nullable<int> ID_of_the_receiving_product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alt_postavok> alt_postavok { get; set; }
        public virtual Поставщик Поставщик { get; set; }
    }
}
