//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склад()
        {
            this.alt_postavok = new HashSet<alt_postavok>();
            this.alt_tov = new HashSet<alt_tov>();
        }
    
        public int id_tov { get; set; }
        public string name { get; set; }
        public int id_category { get; set; }
        public string Description { get; set; }
        public int price { get; set; }
        public string manufacturer { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> cost { get; set; }
        public byte[] img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alt_postavok> alt_postavok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alt_tov> alt_tov { get; set; }
        public virtual Category Category { get; set; }
    }
}
